# yamllint disable rule:comments-indentation
---
# certificates_directory: '/config/certificates/'
theme: 'dark'

## Options are totp, webauthn, mobile_push.
# default_2fa_method: ''

##
## Server Configuration
##
server:
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

##
## Log Configuration
##
# log:
  ## Level of verbosity for logs: info, debug, trace.
  # level: 'debug'

  ## Format the logs are written as: json, text.
  # format: 'json'

  ## File path where the logs will be written. If not set logs are written to stdout.
  # file_path: '/config/authelia.log'

  ## Whether to also log to stdout when a log_file_path is defined.
  # keep_stdout: false

##
## TOTP Configuration
##
## Parameters used for TOTP generation.
# totp:
  ## Disable TOTP.
  # disable: false

  ## The issuer name displayed in the Authenticator application of your choice.
  # issuer: 'authelia.com'

  ## The TOTP algorithm to use.
  ## It is CRITICAL you read the documentation before changing this option:
  ## https://www.authelia.com/c/totp#algorithm
  # algorithm: 'SHA1'

  ## The number of digits a user has to input. Must either be 6 or 8.
  ## Changing this option only affects newly generated TOTP configurations.
  ## It is CRITICAL you read the documentation before changing this option:
  ## https://www.authelia.com/c/totp#digits
  # digits: 6

  ## The period in seconds a Time-based One-Time Password is valid for.
  ## Changing this option only affects newly generated TOTP configurations.
  # period: 30

  ## The skew controls number of Time-based One-Time Passwords either side of the current one that are valid.
  ## Warning: before changing skew read the docs link below.
  # skew: 1
  ## See: https://www.authelia.com/c/totp#input-validation to read
  ## the documentation.

  ## The size of the generated shared secrets. Default is 32 and is sufficient in most use cases, minimum is 20.
  # secret_size: 32

  ## The allowed algorithms for a user to pick from.
  # allowed_algorithms:
  # - 'SHA1'

  ## The allowed digits for a user to pick from.
  # allowed_digits:
  # - 6

  ## The allowed periods for a user to pick from.
  # allowed_periods:
  # - 30

  ## Disable the reuse security policy which prevents replays of one-time password code values.
  # disable_reuse_security_policy: false


webauthn:
  disable: false
  enable_passkey_login: true
  display_name: 'loganhill.nz'
  timeout: '60 seconds'

identity_validation:
  reset_password:

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'

authentication_backend:
  refresh_interval: '1m'
  ldap:
    implementation: 'lldap'
    address: 'ldap://lldap:3890'
    base_dn: 'dc=loganhill,dc=nz'
    user: 'cn=bind_user,ou=people,dc=loganhill,dc=nz'
    # password:
    #password_reset:
    #  disable: false
    #password_change:
    #  disable: false

password_policy:
  standard:
    enabled: false
    min_length: 8

access_control:
  default_policy: 'two_factor'

session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '12 months'
  cookies:
  - domain: 'loganhill.nz'
    authelia_url: 'https://auth.loganhill.nz'
    default_redirection_url: 'https://jellyseerr.loganhill.nz'
    name: 'authelia_session'
    same_site: 'lax'
    inactivity: '5m'
    expiration: '1h'
    remember_me: '12 months'

regulation:
  modes:
    - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '60 minutes'

storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    timeout: '5 seconds'

notifier:
  smtp:
    address: 'submission://loganhill-nz.mail.protection.outlook.com:25'
    timeout: '5s'
    sender: "Authelia <auth@loganhill.nz>"
    identifier: 'Authelia'
    subject: "[Authelia] {title}"
    startup_check_address: 'me@loganhill.nz'
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false

totp:
  disable: false
  issuer: 'KiwiNest'
  algorithm: 'sha1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
  disable_reuse_security_policy: false

#identity_providers:
#  oidc:
#    clients:
#      - client_id: jellyfin
#        client_name: Jellyfin
#        client_secret: <redacted>
#        token_endpoint_auth_method: client_secret_post
#        authorization_policy: one_factor
#        redirect_uris:
#          - https://jellyfin.loganhill.nz/sso/OID/redirect/authelia

...
