services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Pacific/Auckland'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '103.250.90.8;202.179.141.8;2407:8b00:f101:10::10;2407:8b00:f102:10::10'
    env_file:
      - .env
    volumes:
      - '/srv/pihole/etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.loganhill.nz`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pihole.middlewares=authentik@docker"

networks:
  proxy:
    name: proxy
    enable_ipv6: true
    external: true
