services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true

    networks:
     # Connect to the 'proxy' overlay network for inter-container communication across nodes
      - proxy
      - immich

    env_file:
      - .env

    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/traefik/certs:/certs:ro
      - /srv/traefik/dynamic:/dynamic:ro
      - /srv/traefik/letsencrypt:/letsencrypt

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/config.toml"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.file.watch=true"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--serversTransport.insecureSkipVerify=true"

      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.propagation.delayBeforeChecks=60"
      - "--certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.letsencrypt.acme.dnsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      # Timeout increase for Immich
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=600s"

  # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      traefik.enable: true
      traefik.docker.network: proxy

      # Dashboard router
      traefik.http.routers.dashboard.rule: Host(`traefik.loganhill.nz`)
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.tls.certresolver: letsencrypt
      traefik.http.routers.dashboard.middlewares: authentik@docker

networks:
  proxy:
    name: proxy
    external: true
  immich:
    name: immich
    external: true
