services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    env_file: 
        - .env
    networks:
      - proxy
    restart: always
    command: tunnel run --token=$TUNNEL_TOKEN

networks:
  proxy:
    name: proxy
    enable_ipv6: true
    external: true