services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on:
      - unifi-db
    links:
      - 'unifi-db:mongo'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=2048
      - MEM_STARTUP=2048
    volumes:
      - /srv/unifi/data:/config
    ports:
      # - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: always
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.loganhill.nz`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.tls.certresolver=letsencrypt"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.docker.network=proxy"

  unifi-db:
    image: docker.io/mongo:4.4.9
    container_name: unifi-db
    environment:
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - /srv/mongo/data:/data/db
      - /srv/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    #ports:
    #  - 27017:27017
    restart: always
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
